# Generated by Django 4.0.3 on 2023-01-24 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0002_rename_owner_appointment_customer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='technician',
            new_name='technician_name',
        ),
        migrations.RenameField(
            model_name='technician',
            old_name='technician',
            new_name='technician_name',
        ),
    ]
